/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.36
 * Generated at: 2025-03-15 15:52:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Acceuil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/Style.css", Long.valueOf(1742052741137L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Accueil</title>\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <style>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(".navbar-brand {\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write(".navbar-light .navbar-brand{\n");
      out.write("    margin-top: 5px;\n");
      out.write("}\n");
      out.write(".nav-link-shadow {\n");
      out.write("    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);\n");
      out.write("}\n");
      out.write(".logo{\n");
      out.write("    display: flex;\n");
      out.write("    gap: 10px;\n");
      out.write("}\n");
      out.write("#nav{\n");
      out.write("\n");
      out.write("    width: 100%;\n");
      out.write("    top: 0;\n");
      out.write("    z-index: 1000;\n");
      out.write("    height: 70px;\n");
      out.write("    background: #ffffff47;\n");
      out.write("    backdrop-filter: blur(15px);\n");
      out.write("\n");
      out.write("}\n");
      out.write(".header{\n");
      out.write("    height:600px;\n");
      out.write("    background: url('https://images.squarespace-cdn.com/content/v1/58339c1d5016e1d0634f9831/1480989204683-COVLJMLUWKBPJPC84XM9/industrial-construction-alabama.jpg') no-repeat bottom right/cover;\n");
      out.write("    /*background: url(\"https://allenif.com/wp-content/uploads/2020/11/hard-hat-plans-tape-measure_website.jpg\") no-repeat bottom right/cover;*/\n");
      out.write("    backdrop-filter: blur(2px);\n");
      out.write("\n");
      out.write("}\n");
      out.write(".header2{\n");
      out.write("\n");
      out.write("    height: 65%;\n");
      out.write("    /*background-color: rgba(4, 9, 30, 0.7);*/\n");
      out.write("    background :url(\"https://en.idei.club/uploads/posts/2023-06/1686013328_en-idei-club-p-building-construction-background-dizain-in-26.jpg\")no-repeat bottom right/cover ;\n");
      out.write("}\n");
      out.write(".nav-link{\n");
      out.write("    font-weight: bold;\n");
      out.write("    color: white;\n");
      out.write("    display: flex;\n");
      out.write("    gap: 5px;\n");
      out.write("}\n");
      out.write(".navbar-expand-lg{\n");
      out.write("    height: 80px;\n");
      out.write("}\n");
      out.write(".title{\n");
      out.write("\n");
      out.write("    width:700px;\n");
      out.write("    margin:159px auto;\n");
      out.write("    color:white;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write(".title > h2{\n");
      out.write("    font-size:40px;\n");
      out.write("    text-transform:uppercase;\n");
      out.write("    font-weight:800;\n");
      out.write("    text-shadow: 0 0 20px white;\n");
      out.write("}\n");
      out.write(".title > h4{\n");
      out.write("    font-size:14px;\n");
      out.write("    text-transform:uppercase;\n");
      out.write("    font-weight:600;\n");
      out.write("    color:white;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container.text-center.my-5 {\n");
      out.write("    color: #ffffff; /* Couleur du texte en blanc */\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("label {\n");
      out.write("    margin-right: 10px;\n");
      out.write("}\n");
      out.write(".navbar-nav{\n");
      out.write("    height: 10%;\n");
      out.write("}\n");
      out.write("/* /////////////////////////////////////////////////////////*/\n");
      out.write("/* les Cards dans la page d'accueil*/\n");
      out.write("\n");
      out.write("\n");
      out.write("body {\n");
      out.write("    font-family: Arial, sans-serif;\n");
      out.write("    background-color: #272424;\n");
      out.write("    color: #333;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write(".body {\n");
      out.write("    font-family: Arial, sans-serif;\n");
      out.write("    background-color: #272424;\n");
      out.write("    color: #333;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("    font-size: 2.5rem;\n");
      out.write("    margin-bottom: 0.5rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("p.text-muted {\n");
      out.write("    font-size: 1.2rem;\n");
      out.write("    color: #6c757d;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card1 {\n");
      out.write("    border: none;\n");
      out.write("    box-shadow:0 1px 5px #ffffff;\n");
      out.write("    transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card1:hover {\n");
      out.write("    transform: translateY(-10px);\n");
      out.write("    box-shadow: 0 4px 8px rgb(255, 218, 7);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card1-title {\n");
      out.write("    font-size: 1.5rem;\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".card1-text {\n");
      out.write("    font-size: 1rem;\n");
      out.write("    color: #666;\n");
      out.write("}\n");
      out.write(".container.text-center.my-5 {\n");
      out.write("    color: #ffffff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("/*//////////*/\n");
      out.write(".description {\n");
      out.write("    font-size: 1em;\n");
      out.write("    color: #fff;\n");
      out.write("    margin-bottom: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn {\n");
      out.write("    font-size: 1em;\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    color: #fff;\n");
      out.write("    background-color: #dca63d;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn:hover {\n");
      out.write("    background-color: #b88a2e;\n");
      out.write("}\n");
      out.write("h1 {\n");
      out.write("    font-size: 3em;\n");
      out.write("    color: #fff;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("\n");
      out.write("    text-transform:uppercase;\n");
      out.write("    font-weight:600;\n");
      out.write("\n");
      out.write("}\n");
      out.write(".bgadd {\n");
      out.write("    background-color: #f8f9fa}\n");
      out.write("\n");
      out.write("\n");
      out.write("/*   Css de la page Afficher les projets */\n");
      out.write(".navbar-brand {\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".titleProjet{\n");
      out.write("\n");
      out.write("    width:700px;\n");
      out.write("    margin:118px auto;\n");
      out.write("    color:white;\n");
      out.write("    text-align: center;\n");
      out.write("\n");
      out.write("\n");
      out.write("}\n");
      out.write(".titleProjet >h1{\n");
      out.write("    font-size: 48px;\n");
      out.write("    font-weight: 600;\n");
      out.write("    color: black;\n");
      out.write("\n");
      out.write("    text-transform:uppercase;\n");
      out.write("\n");
      out.write("    text-shadow: 0 0 20px white;\n");
      out.write("\n");
      out.write("}\n");
      out.write(".titre{\n");
      out.write("    font-family: \"Poppins\", sans-serif;\n");
      out.write("    color: rgba(255, 255, 255, 0.95);\n");
      out.write("    line-height: 1.2em;\n");
      out.write("    margin-bottom: 55px;\n");
      out.write("    margin-top: 55px;\n");
      out.write("    font-weight: 600;\n");
      out.write("    font-size: 36px;\n");
      out.write("}\n");
      out.write(".para{\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-content: center;\n");
      out.write("    margin: 20px auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(".imgCard{\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("/*  button add\n");
      out.write(".add-project-btn {\n");
      out.write("    display: inline-block;\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    font-size: 16px;\n");
      out.write("    color: #fff;\n");
      out.write("    background-color: #007bff;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    transition: background-color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".add-project-btn:hover {\n");
      out.write("    background-color: #0056b3;\n");
      out.write("}\n");
      out.write(".btnAjou{\n");
      out.write("    margin-bottom: 15px;\n");
      out.write("    display: flex;\n");
      out.write("\n");
      out.write("    flex-wrap: wrap;\n");
      out.write("    justify-content: left;\n");
      out.write("    padding: 0px 0px 0px 20px;\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("/* la page Ajooouter */\n");
      out.write("\n");
      out.write("/* Styles de base pour le bouton */\n");
      out.write(".add-project-btn {\n");
      out.write("    background-color: #dca63d; /* Couleur de fond dorÃ©e */\n");
      out.write("    color: black; /* Couleur du texte */\n");
      out.write("    border: none;\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    text-align: center;\n");
      out.write("    text-decoration: none;\n");
      out.write("    display: inline-block;\n");
      out.write("    font-size: 16px;\n");
      out.write("    margin: 4px 36px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    border-radius: 4px;\n");
      out.write("    transition: background-color 0.3s ease, color 0.3s ease, text-shadow 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Ombre pour le texte */\n");
      out.write(".add-project-btn {\n");
      out.write("    font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Effet hover */\n");
      out.write(".add-project-btn:hover {\n");
      out.write("    background-color: #b8860b; /* Couleur de survol dorÃ©e plus foncÃ©e */\n");
      out.write("    color: white; /* Couleur du texte au survol */\n");
      out.write("    text-shadow: 1px 1px 2px rgba(255, 255, 255, 0.7); /* Ombre de texte au survol */\n");
      out.write("}");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<header class=\"header\">\n");
      out.write("\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light\" id=\"nav\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"logo\">\n");
      out.write("                <img src=\"https://i.ibb.co/FqvDG8v/Design-sans-titre-6.png\" alt=\"image de logo\" style=\"width: 50px; height: 50px;\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">ConstructionXpert</a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("                <ul class=\"navbar-nav ml-auto\">\n");
      out.write("                    <li class=\"nav-item active\">\n");
      out.write("                        <a class=\"nav-link nav-link-shadow\" href=\"#\">Accueil</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item active\">\n");
      out.write("                        <a class=\"nav-link nav-link-shadow\" href=\"/ConstructionXpert_Services_Solution_war_exploded/AfficherProjet\">Projets</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item active\">\n");
      out.write("                        <a class=\"nav-link nav-link-shadow\" href=\"#\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"title\">\n");
      out.write("        <h1> Gestion de Projets de Construction Efficace </h1>\n");
      out.write("        <p class=\"description\">Planifiez, organisez et gérez vos projets de construction avec précision et efficacité grâce à une interface intuitive qui permet de visualiser, mettre à jour et supprimer des projets, des tâches et des ressources, tout en assurant la sécurité et l'intégrité de vos données.</p>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ConstructionXpert_Services_Solution_war_exploded/AfficherProjet\" class=\"btn\">GET STARTED</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container text-center my-5\">\n");
      out.write("    <h2>Ce que nous offrons à nos clients</h2>\n");
      out.write("    <p class=\"text-muted\">Construisez l'avenir avec notre application de gestion de projets de construction, efficace et durable.</p>\n");
      out.write("    <div class=\"row mt-4\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card1\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <h5 class=\"card-title\">Gestion de Projet</h5>\n");
      out.write("                    <p class=\"card-text\">\n");
      out.write("                        La gestion des projets consiste à planifier, organiser et suivre toutes les activités nécessaires pour atteindre les objectifs d'un projet.\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card1\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <h5 class=\"card-title\">Gestion des Taches</h5>\n");
      out.write("                    <p class=\"card-text\">\n");
      out.write("                        La gestion des tâches consiste à planifier, organiser et suivre toutes les activités nécessaires pour atteindre les objectifs d'un projet.\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("            <div class=\"card1\">\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                    <h5 class=\"card-title\">Gestion des Ressources</h5>\n");
      out.write("                    <p class=\"card-text\">\n");
      out.write("                        La gestion des ressources implique la planification, l'allocation et le suivi des ressources nécessaires à un projet, comme le personnel, les matériaux et le temps.\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Bootstrap JS -->\n");
      out.write("<script>\n");
      out.write("    window.addEventListener(\"scroll\", function () {\n");
      out.write("        let navbar = document.querySelector(\".navbar\");\n");
      out.write("        if (window.scrollY > 150) {\n");
      out.write("            navbar.classList.add(\"bgadd\");\n");
      out.write("        } else {\n");
      out.write("            navbar.classList.remove(\"bgadd\");\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js\"></script>\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
